apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: edu-sleepy-engelbart
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80