apiVersion: v1
kind: Service
metadata:
  name: django-web
  namespace: edu-sleepy-engelbart
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: django-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30031
