apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "@monthly"
  startingDeadlineSeconds: 10
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
            - name: django-clearsessions
              image: django_app:latest
              imagePullPolicy: IfNotPresent
              command: [ "/bin/sh" ]
              args: [ "-c", "python manage.py clearsessions" ]
              envFrom:
                - secretRef:
                    name: django-web-secret
          restartPolicy: OnFailure