apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web
  labels:
    app.kubernetes.io/name: django-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: django-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-web
        app.kubernetes.io/instance: django-web-1
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: django-app
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
      - name: django-web
        image: django_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-web-secret
                key: SECRET_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-web-secret
                key: DATABASE_URL
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: django-web-secret
                key: ALLOWED_HOSTS
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: django-web-secret
                key: DEBUG
