apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-django-sessions
spec:
  schedule: "@monthly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clear-django-sessions
              image: django_app:latest
              imagePullPolicy: IfNotPresent
              command: [ "/bin/sh" ]
              args: [ "-c", "python manage.py clearsessions" ]
              env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: django-web-secret
                      key: SECRET_KEY
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: django-web-secret
                      key: DATABASE_URL
                - name: ALLOWED_HOSTS
                  valueFrom:
                    secretKeyRef:
                      name: django-web-secret
                      key: ALLOWED_HOSTS
                - name: DEBUG
                  valueFrom:
                    secretKeyRef:
                      name: django-web-secret
                      key: DEBUG
          restartPolicy: OnFailure