apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web
  labels:
    app.kubernetes.io/name: django-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: django-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-web
        app.kubernetes.io/instance: django-web-1
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: django-app
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
      - name: django-web
        image: django_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-web-secret
                key: SECRET_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-web-secret
                key: DATABASE_URL
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: django-web-secret
                key: ALLOWED_HOSTS
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: django-web-secret
                key: DEBUG
---
apiVersion: v1
kind: Service
metadata:
  name: django-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: django-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: star-burger.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-web
            port:
              number: 80