apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
      - name: django-migrate
        image: django_app:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "python manage.py migrate"]
        envFrom:
          - secretRef:
              name: django-web-secret
      restartPolicy: OnFailure
  backoffLimit: 4