apiVersion: v1
kind: Secret
metadata:
  name: django-web-secret
type: Opaque
data:
  SECRET_KEY: bXktc2VjcmV0LWtleQ==
  DATABASE_URL: cG9zdGdyZXM6Ly9teXVzZXI6bXlwYXNzQHBvc3RncmVzLWRiLXBvc3RncmVzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL215ZGF0YWJhc2U=
  ALLOWED_HOSTS: Kg==
  DEBUG: RmFsc2U=